apiVersion: v1
name: istio-ingress
# This version is never actually shipped. istio/release-builder will replace it at build-time
# with the appropriate version
version: 1.13.3
appVersion: 1.13.3
tillerVersion: ">=2.7.2"
description: Helm chart for deploying Istio gateways
keywords:
  - istio
  - ingressgateway
  - gateways
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
