logging:
  level:
    root: DEBUG

spring:
  application:
    name: event-reload
  cloud:
    kubernetes:
      reload:
        enabled: true
        strategy: shutdown
        mode: event
        namespaces:
          - right
        monitoring-config-maps: true
