spring:
  application:
    name: event-reload
  cloud:
    kubernetes:
      secrets:
        enabled: false
      reload:
        enabled: true
        strategy: refresh
        mode: event
        namespaces:
          - right
        monitoring-config-maps: true
