logging:
  level:
    org:
      springframework:
        cloud:
          kubernetes:
            commons: debug

spring:
  application:
    name: poll-reload
  cloud:
    kubernetes:
      reload:
        enabled: true
        monitoring-config-maps: true
        strategy: refresh
        mode: polling
        period: 5000
      config:
        paths:
          - /tmp/application.properties
  config:
    import: "kubernetes:"

