spring:
  application:
    name: poll-reload
  config:
    import: "kubernetes:"
  cloud:
    kubernetes:
      reload:
        enabled: true
        monitoring-config-maps: true
        strategy: refresh
        mode: polling
        period: 5s
