spring:
  application:
    name: poll-reload-mount
  config:
    import: "kubernetes:,configtree:/tmp/,vault://"

management:
  endpoint:
    refresh:
      enabled: true
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
