#logging:
#  level:
#    org.springframework: DEBUG
#
spring:
  application:
    name: spring-cloud-kubernetes-client-configuration-watcher-configmap-app-a
  cloud:
    bus:
      refresh:
        enabled: false
      enabled: true
      destination: multiple-apps
    stream:
      default-binder: kafka
management:
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8080
