name: download docker images
description: download docker images
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      with:
        path: /tmp/docker/images
        key: docker-images-cache-${{ env.GITHUB_RUN_ID }}
        restore-keys: docker-images-cache-${{ env.GITHUB_RUN_ID }}


