server:
  servlet:
    context-path: /discoveryclient-it

spring:
  cloud:
    kubernetes:
      discovery:
        discoveryServerUrl: http://spring-cloud-kubernetes-discoveryserver
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
