# we are using a JKube fragment to ensure that NodePort is used correctly
kind: Service
apiVersion: v1
metadata:
  name: ${project.artifactId}
  labels:
    app: ${project.artifactId}
spec:
  selector:
    app: ${project.artifactId}
  ports:
    - protocol: TCP
      port: 8080
      nodePort: ${nodeport.value}
  type: NodePort
