apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: spring-cloud-kubernetes-core-k8s-client-it
  name: istio-test-rb
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: istio-test
subjects:
  - kind: ServiceAccount
    name: spring-cloud-kubernetes-istio-serviceaccount
    namespace: istio-test
