spring:
  application:
    name: app-b
  cloud:
    bus:
      refresh:
        enabled: false #disable this because we are going to provide our own refresh listener for testing purposes
      enabled: true
      destination: multiple-apps
    stream:
      default-binder: kafka
management:
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8081
