apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps", "discovery.k8s.io", "coordination.k8s.io"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets", "endpointslices", "leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
