management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


spring:
  main:
    allow-bean-definition-overriding: true

  cloud:
    kubernetes:
      discovery:
        discoveryServerUrl: http://spring-cloud-kubernetes-discoveryserver
