name: build integration tests project without tests
description: build integration tests project without tests
runs:
  using: "composite"
  steps:

    - name: build integration tests project without tests
      shell: bash
      run: |
        
        cd spring-cloud-kubernetes-test-support
        .././mvnw clean install -U
        cd ..
        
        echo "==================================="
        ls ~/.m2/repository/org/springframework/cloud/spring-cloud-kubernetes-fabric8-discovery/3.1.0-SNAPSHOT
        echo "==================================="
        
        cd spring-cloud-kubernetes-integration-tests
        # build the images, but dont run the tests
        .././mvnw -T 1C clean install -DskipTests
        cd ..
