name: save controller docker images
description: save controller docker images
runs:
  using: "composite"
  steps:
    - name: save controller docker images
      shell: bash
      run: |
        echo 'saving controller images with tag : $PROJECT_TAG'
        cd spring-cloud-kubernetes-controllers
        integ_tests_command="mvn -Dexec.executable='echo' -Dexec.args='${project.artifactId}' exec:exec -q | grep -v 'spring-cloud-kubernetes-controllers'"
        while read integ_test; do
          docker save -o /tmp/docker/images/${integ_test}.tar docker.io/springcloud/${integ_test}:$PROJECT_TAG
        done < <(eval $integ_tests_command)
        cd ..
