name: run and save test times when cache present
description: run and save test times when cache present
runs:
  using: "composite"

  steps:
    - name: restore test times cache
      uses: actions/cache/restore@v3
      with:
        path: /tmp/sorted.txt
        key: ${{ runner.os }}-spring-cloud-k8s-cache-of-test-times-${{ github.run_id }}
        restore-keys: ${{ runner.os }}-spring-cloud-k8s-cache-of-test-times-

    - name: show cached test times
      shell: bash
      run: cat /tmp/sorted.txt

    - name: find all tests
      shell: bash
      run: |
        PLAIN_TEST_CLASSNAMES=($(cat /tmp/tests.txt | grep 'spring.cloud.k8s.test.to.run' | awk '{print $3}'))
        echo "${PLAIN_TEST_CLASSNAMES[@]}"
