name: maven-build-with-dry-run-for-tests
description: maven-build-with-dry-run-for-tests
runs:
  using: "composite"
  steps:
    - name: maven-build-with-dry-run-for-tests
      shell: bash
      run: |
          # find all the tests that are supposed to be run, but don't actually run them.
          # this is achieved via: 'spring.cloud.k8s.skip.tests=true' in DisabledTestsCondition
          ./mvnw test -B -Dskip.build.image=true -Dspring.cloud.k8s.skip.tests=true \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=error \
                -T 1C -q > /tmp/tests.txt

    - name: show result
      if: always()
      shell: bash
      run: cat /tmp/tests.txt

    - name: upload test
      uses: actions/upload-artifact@v3
      with:
        name: tests.txt
        path: /tmp/tests.txt

