spring:
  application:
    name: non-app
  cloud:
    bus:
      refresh:
        enabled: false
      enabled: true
      destination: app
      id: app
    stream:
      default-binder: rabbit
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
management:
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8080
