name: echo saved images
description: echo saved images
runs:
  using: "composite"
  steps:
    - name: echo saved images
      shell: bash
      run: |
        VIEW=$(ls -l /tmp/docker/images)
        echo "${VIEW}"
