/*
 * Copyright 2013-2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.cloud.kubernetes.integration.tests.commons;

import java.io.File;

/**
 * @author wind57
 */
final class Constants {

	private Constants() {

	}

	/**
	 * this path is generated by the pipeline of github actions.
	 */
	static final String TMP_IMAGES = "/tmp/docker/images";

	/**
	 * Temporary folder where to load images.
	 */
	static final String TEMP_FOLDER = new File(System.getProperty("java.io.tmpdir")).getAbsolutePath();

	/**
	 * where is the version situated.
	 */
	static final String KUBERNETES_VERSION_FILE = "META-INF/springcloudkubernetes-version.txt";

}
