= Examples

Spring Cloud Kubernetes tries to make it transparent for your applications to consume Kubernetes Native Services
following the Spring Cloud interfaces. For your applications, you will only need to change the implementation of these interfaces
if you were using different DiscoveryClient or PropertySourceLocator implementations.

The following projects highlight the usage of these dependencies and demonstrate how these libraries can be used from any Spring Boot application.

List of examples using these projects:

- https://github.com/spring-cloud/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-examples[Spring Cloud Kubernetes Examples]: the ones located inside this repository.
- Spring Cloud Kubernetes Full Example: Minions and Boss
	- https://github.com/salaboy/spring-cloud-k8s-minion[Minion]
	- https://github.com/salaboy/spring-cloud-k8s-boss[Boss]
- Spring Cloud Kubernetes Full Example: https://github.com/salaboy/s1p_docs[SpringOne Platform Tickets Service]
- https://github.com/salaboy/s1p_gateway[Spring Cloud Gateway with Spring Cloud Kubernetes Discovery and Config]
- https://github.com/salaboy/showcase-admin-tool[Spring Boot Admin with Spring Cloud Kubernetes Discovery and Config]





