name: persist docker images
description: persist docker images
runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@v3
      with:
        name: tar-images
        path: /tmp/docker/images


