apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-cloud-kubernetes-client-config-it
  name: spring-cloud-kubernetes-client-config-it-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-kubernetes-client-config-it
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-cloud-kubernetes-client-config-it
    spec:
      serviceAccountName: spring-cloud-kubernetes-serviceaccount
      containers:
        - image: springcloud/spring-cloud-kubernetes-client-config-it:2.0.4-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: spring-cloud-kubernetes-client-config-it
          resources: {}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_CLOUD_KUBERNETES_RELOAD_MODE
              value: polling
status: {}
