global:
  # Used to locate istiod.
  istioNamespace: "istio-system"

base:
  # Validation webhook configuration url
  # For example: https://$remotePilotAddress:15017/validate
  validationURL: ""

istiodRemote:
  # Sidecar injector mutating webhook configuration url
  # For example: https://$remotePilotAddress:15017/inject
  injectionURL: ""

# Revision is set as 'version' label and part of the resource names when installing multiple control planes.
revision: ""

sidecarInjectorWebhook:
  # This enables injection of sidecar in all namespaces,
  enableNamespacesByDefault: false

