logging:
  level:
    root: DEBUG

spring:
  application:
    name: event-reload
  config:
    import: "kubernetes:"
  cloud:
    kubernetes:
      reload:
        enabled: true
        strategy: shutdown
        mode: event
        monitoring-secrets: true
        monitoring-configMaps: false
      secrets:
        enabled: true
        enable-api: true

