spring:
  application:
    name: poll-reload-mount
  cloud:
    kubernetes:
      reload:
        enabled: true
        monitoring-config-maps: true
        strategy: shutdown
        mode: polling
        period: 5000
  config:
    import: "kubernetes:,configtree:/tmp/"

