antora:
  extensions:
    - '@springio/antora-extensions/partial-build-extension'
    - require: '@springio/antora-extensions/latest-version-extension'
    - require: '@springio/antora-extensions/inject-collector-cache-config-extension'
    - '@antora/collector-extension'
    - '@antora/atlas-extension'
    - require: '@springio/antora-extensions/root-component-extension'
      root_component_name: 'cloud-kubernetes'
    - '@springio/antora-extensions/static-page-extension'
site:
  title: Spring Cloud Kubernetes
  url: https://docs.spring.io/spring-cloud-kubernetes/reference/
content:
  sources:
    - url: ./..
      branches: HEAD
      start_path: docs
      worktrees: true
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-cloud
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    chomp: 'all'
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
  sourcemap: true
urls:
  latest_version_segment: ''
runtime:
  log:
    failure_level: warn
    format: pretty
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.2/ui-bundle.zip