apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: spring-cloud-kubernetes-client-config-it
build:
  artifacts:
  - image: springcloud/spring-cloud-kubernetes-client-config-it
    custom:
      buildCommand: "../../mvnw clean install -Pskaffold"
      dependencies:
        paths:
          - src
          - pom.xml

profiles:
  - name: polling
    deploy:
      kubectl:
        manifests:
          - k8s/deployment-polling-it.yaml
          - k8s/service-it.yaml
          - k8s/configmap.yaml
          - k8s/secret.yaml
          - ../permissions.yaml

deploy:
  kubectl:
    manifests:
    - k8s/deployment-it.yaml
    - k8s/service-it.yaml
    - k8s/configmap.yaml
    - k8s/secret.yaml
    - ../permissions.yaml
