name: setup project
description: setup project
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: test step
      shell: bash
      run: |
        ls -l /
