apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-cloud-kubernetes-discoveryclient-it
  name: spring-cloud-kubernetes-discoveryclient-it
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-cloud-kubernetes-discoveryclient-it
  type: ClusterIP
status:
  loadBalancer: {}
